# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPartida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PartidaJugada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esGuanyador', models.BooleanField()),
                ('numFormatges', models.IntegerField()),
                ('idPartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partides.Partida')),
                ('nomJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadors.Jugador')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partidajugada',
            unique_together=set([('idPartida', 'nomJugador')]),
        ),
    ]
