# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, unique=True)),
                ('nomCategoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('textPregunta', models.TextField()),
                ('idColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntes.Categoria')),
                ('idPartida', models.ManyToManyField(to='partides.Partida')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('idResposta', models.AutoField(primary_key=True, serialize=False)),
                ('textResposta', models.CharField(max_length=200)),
                ('esCorrecta', models.BooleanField()),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntes.Pregunta')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together=set([('idResposta', 'idPregunta')]),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together=set([('idPregunta', 'idColor')]),
        ),
    ]
